### ISSUE TITLE
User can various cuisine types from dropdown menu

### ISSUE THREAD

**Issue by Jykwon24** [Jykwon24/ajax-project#1]
## ⚙️ Feature

Users will want to view the page and be able to select which type of cuisine they would like

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive form with dropdown menu listing the available cuisine types and submit button to execute

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="406" alt="Screen Shot 2022-02-13 at 11 43 56 AM" src="https://user-images.githubusercontent.com/86754302/153771960-3c07f91c-ab11-4351-8a70-5924ba98f314.png">
<img width="387" alt="Screen Shot 2022-02-13 at 11 44 02 AM" src="https://user-images.githubusercontent.com/86754302/153771964-4f71f89b-5161-4494-aa44-5a89a8b894ef.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create HTML doc
- [x] create divs containing each item on the site (logo, heading, buttons)
- [x] create a 'favorites' button that will contain the favorites list.
- [x] create a form? to contain the dropdown menu and corresponding submit button
- [x] list out each cuisine type for the drop down menu
- [x] once type is selected, display type
- [x] create a data model that contains information for the cuisine type and other information.
- [x] remove all unnecessary CSS styling
- [x] test functionality
