### ISSUE TITLE
Issue-6-refactor

### ISSUE THREAD

**Issue by Jykwon24** [Jykwon24/ajax-project#11]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [ ] organize page giving data-view classes to the 3 main pages on the site
- [ ] 
- [ ] refactor code, removing location.reload.
- [ ] set data-view attributes to easily swap through 'screens'
- [ ] ...
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
