### ISSUE TITLE
User can randomly generate recipe based on cuisine type

### ISSUE THREAD

**Issue by Jykwon24** [Jykwon24/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can generate a random recipe based on their cuisine selection once submit is pressed.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create button that will update data model and generate random recipe from the recipes API.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="391" alt="Screen Shot 2022-02-13 at 12 00 53 PM" src="https://user-images.githubusercontent.com/86754302/153772565-d70f9356-9c8b-4704-a448-9014e2e3fc69.png">
<img width="401" alt="Screen Shot 2022-02-13 at 12 01 08 PM" src="https://user-images.githubusercontent.com/86754302/153772575-49d944e1-86cc-4b8b-8241-830a8154b701.png">
<img width="397" alt="Screen Shot 2022-02-13 at 12 01 13 PM" src="https://user-images.githubusercontent.com/86754302/153772578-21498681-7508-4bdd-b1df-8ab1dc8b04ca.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create submit button for form
- [x] style the submit button
- [x] set submit button div with display hidden
- [x] once cuisine type is selected, display the submit button
- [x] add eventlistener for when the submit button is clicked to generate recipe from API
- [x] figure out way to use the value class from the select element to pull a recipe from API
- [x] display recipe from API on page
- [x] set logo and main page wording to hidden
- [x] display smaller sized logo on top part of page
- [x] add 'add to favorites' button on the right side of the page
- [x] add eventlistener for when you click on logo on top part of page, goes to main menu
- [x] test functionality
- [x] remove all unnecessary CSS styling
- [x] fix bugs and errors
