### ISSUE TITLE
User can save a favorite recipe to a list

### ISSUE THREAD

**Issue by Jykwon24** [Jykwon24/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a favorite recipe to their favorites list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once recipe is generated user will be able to save the recipe to their favorites

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="396" alt="Screen Shot 2022-02-13 at 12 01 25 PM" src="https://user-images.githubusercontent.com/86754302/153772707-d65f2522-f69e-4230-ba5f-4d785dd4d26e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create empty recipeObj
- [x] store API recipe data into the object
- [x] create a ul element on the HTML
- [x] create a li DOM to store the recipe on the favorites list
- [x] decide how to display the recipes on the favorites list
- [x] store relevant recipe information to favorites list once user 'click's' to save to favorites
- [x] add an eventListener to the favorites button on the top menu
- [x] fix all useless css
- [x] test functionality and fix errors
