### ISSUE TITLE
User can view their listed favorite recipes

### ISSUE THREAD

**Issue by Jykwon24** [Jykwon24/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their listed favorite recipes

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view their listed favorite recipes on new page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="390" alt="Screen Shot 2022-02-13 at 12 06 18 PM" src="https://user-images.githubusercontent.com/86754302/153772776-be082508-6f1a-4b8a-adbd-a57033327ab2.png">
<img width="397" alt="Screen Shot 2022-02-13 at 12 06 23 PM" src="https://user-images.githubusercontent.com/86754302/153772780-50406530-6ac2-492c-9c3e-17e278ceea52.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] complete addEventListener function on the top bar favorites button
- [x] complete render function for the DOM li list of favorited recipes
- [x] once clicked display the favorites list
- [x] if empty, show empty favorites list message
- [x] pull from datamodel the information on the recipes that were favorited
- [x] if not empty display the favorited recipes list
- [x] fix all errors
- [x] remove unnecessary CSS styling
