### ISSUE TITLE
User can remove recipes from their list

### ISSUE THREAD

**Issue by Jykwon24** [Jykwon24/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove recipes from their list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can remove recipes from their list by clicking edit button to remove

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="384" alt="Screen Shot 2022-02-13 at 12 07 06 PM" src="https://user-images.githubusercontent.com/86754302/153772828-c53f5aa6-8fc5-4b4d-ad6f-904133858df1.png">
<img width="410" alt="Screen Shot 2022-02-13 at 12 07 12 PM" src="https://user-images.githubusercontent.com/86754302/153772833-31bead1e-3776-4903-80aa-f87ba971c827.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add button or symbol indicating edit feature
- [x] possibly add another to view the recipe
- [x] create div for the modal
- [x] add buttons cancelling or confirming
- [x] wording asking 'Delete recipe from list?'
- [x] create a modal asking to confirm deletion of favorite recipe
- [x] add an Eventlistener to carry out the task of deleting recipe
- [x] finish out thinking and implementing viewing the favorited recipe
- [x] will likely need to create a new render function to display recipe when clicked from favorites
- [x] fix all CSS styling
- [x] fix all bugs and errors
